keycloak:
  realm: TacticalWolves
  resource: TacticalWolves-Admin
  auth-server-url: https://84.86.167.197:8082/auth
  credentials:
    secret: ce055536-ed4c-49e1-8b9b-a04d8ef04d5b
  disable-trust-manager: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://84.86.167.197:8761/eureka/
  instance:
    hostname: localhost
spring:
  application:
    name: PROVIDER-SERVICE

